version: '3'


services:

  backend:
    build:
      context: grpc-spring-course
    container_name: backend
    tty: true
    ports:
      - 9090:9090
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdatabase
    networks:
      - app_network


networks:
  app_network:
    driver: bridge